name: KitPvP
author: dustin and braden
version: 100000.0
main: com.dustinbraden.KitPvP.Main
description: Kit PvP plugin
commands:
  Knight:
    description: Gives you knight kit
  Archer:
    description: Gives you Archer kit